#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false

# Disable password authentication fo root user
ssh_pwauth: false

# Install required packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

# Install Docker + Docker Compose & Start Docker
runcmd:
  - mkfs.${volume_filesystem} ${filesystem_cmd_opt} ${linux_device}
  - mkdir /mnt/${mount_dir_name}
  - mount -o discard,defaults ${linux_device} /mnt/${mount_dir_name}
  - echo '${linux_device} /mnt/${mount_dir_name} ${volume_filesystem} discard,nofail,defaults 0 0' >> /etc/fstab
  # Add repository
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - ufw allow OpenSSH
  - ufw --force enable
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update -y
  # Install Docker Engine
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - sed -i -e "s|ExecStart=/usr/bin/dockerd|ExecStart=/usr/bin/dockerd --data-root=/mnt/${mount_dir_name}|g" /lib/systemd/system/docker.service
  - systemctl daemon-reload
  - systemctl restart docker
  - systemctl enable docker
  - docker swarm init

final_message: "The system is ready, after $UPTIME seconds"
