#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: false

# Disable password authentication for root user
ssh_pwauth: false

# Install required packages
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

# Install Docker + Docker Compose & Start Docker
runcmd:
  - mkfs.${volume_filesystem} ${filesystem_cmd_opt} ${linux_device}
  - mkdir /mnt/${mount_dir_name}
  - mount -o discard,defaults ${linux_device} /mnt/${mount_dir_name}
  - echo '${linux_device} /mnt/${mount_dir_name} ${volume_filesystem} discard,nofail,defaults 0 0' >> /etc/fstab
  # Add repository
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - ufw allow OpenSSH
  - ufw --force enable
  - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update -y
  # Install Docker Engine
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - sed -i -e "s|ExecStart=/usr/bin/dockerd|ExecStart=/usr/bin/dockerd --data-root=/mnt/${mount_dir_name}|g" /lib/systemd/system/docker.service
  - systemctl daemon-reload
  - systemctl restart docker
  - systemctl enable docker
  # Initialize swarm only if this is the first node
  - |
    if [ "${is_first_node}" = "true" ]; then
      echo "Initializing Docker Swarm as manager..."
      docker swarm init
      echo "Docker Swarm initialized successfully!"
    else
      echo "Joining Docker Swarm as worker node..."
      # Wait for manager to be ready and retry joining
      max_attempts=30
      attempt=1
      
      while [ $attempt -le $max_attempts ]; do
        echo "Attempt $attempt/$max_attempts: Trying to join swarm..."
        
        # Get the worker join token from the manager
        if docker swarm join --token $(ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 root@${manager_ip} "docker swarm join-token worker -q") ${manager_ip}:2377 2>/dev/null; then
          echo "Successfully joined Docker Swarm as worker!"
          break
        else
          echo "Failed to join swarm, attempt $attempt/$max_attempts"
          if [ $attempt -lt $max_attempts ]; then
            echo "Waiting 10 seconds before retry..."
            sleep 10
          fi
          attempt=$((attempt + 1))
        fi
      done
      
      if [ $attempt -gt $max_attempts ]; then
        echo "Failed to join swarm after $max_attempts attempts. Manual intervention may be required."
      fi
    fi

final_message: "The system is ready, after $UPTIME seconds"
